services:
  podfetch:
    image: samuel19982/podfetch:latest
    container_name: podfetch
    user: 0:0
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./assets:/app/podcasts
      - ./config/podfetch:/app/db
    environment:
      - POLLING_INTERVAL=30
      - SERVER_URL=http://localhost:8000
      - DATABASE_URL=sqlite:///app/db/podcast.db

  audioadremover:
    build:
      context: ./AudioDupDetector
    container_name: audioadremover
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./assets/:/app/assets
      - ./complete:/app/complete
    tmpfs:
      - /app/temp:rw,mode=1777
    restart: always

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - "80:80"
    volumes:
      #- </path/to/audiobooks>:/audiobooks
      - ./complete:/podcasts
      - ./config/audiobookshelf:/config
      - ./config/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/Chicago

  cleaner:
    image: bash:latest
    container_name: podcast-cleaner
    volumes:
      - ./complete:/complete
      - ./assets:/assets
      - ./cleaner.sh:/app/cleaner.sh
    entrypoint: ["/usr/local/bin/bash", "/app/cleaner.sh"]
    restart: unless-stopped